### ISSUE TITLE
libqt5pas version

### ISSUE THREAD

**Issue by Begasus** [roired/CudaText-Haiku#2]
Hello @roired I'm looking into creating a recipe for libqt5pas, using the sources from https://github.com/davidbannon/libqt5pas as mentioned in https://wiki.freepascal.org/Qt5_Interface
Could you tell what version of libqt5pas you are using atm?
PS, great work so far! :+1:

**Comment by Begasus** [comment]
Found out, you added the 1.2.6 version, current version is at 1.2.9 :)

**Comment by roired** [comment]
@Begasus,
XD
I added the 1.2.6 version because that was the one that was available at the Hakilo repo where I got FreePascal and Lazarus. That is the only reason for it. Nonetheless, not sure if it would work with 1.2.9. Need to check that. :)

Regards,
RR

**Comment by Begasus** [comment]
PR created for version 1.2.9 :) https://github.com/haikuports/haikuports/pull/5988
Could you check it out @roired ?

**Comment by Begasus** [comment]
@roired pushed the PR for libqt5pas (1.2.9) earlier and it builds ok on the buildbot, should be available for install now, could you have another look?

**Comment by roired** [comment]
Good day @Begasus,

I just checked the libqt5pas package from Haikuports. There is an issue that I find, which is that also are needed links to the lib (libQt5Pas.so, and libQt5Pas.so.1.2). 
I tried to make them in the setup script but looks like it didn't work. Maybe I'm missing something there.

I'll review the shell script again.
Regards,
RR

**Comment by roired** [comment]
@Begasus, 
I just launched CudaText against libqt5pas 1.2.9 right now and it did work. Had to add the links in the /boot/system/lib folder including them in the package. Strange. Yesterday didn't work, today it does. I'm puzzled. But seems to work. No other libqt5pas is installed but the one you provided at Haikuports. So it seems it's a GO?

Regards,
RR

**Comment by Begasus** [comment]
@roired I'm not sure how you build CudaText, but it seems a deppendency is missing from the recipe (if you are using that), if I knew how you build CudaText I could have a look into it (when time permits), glad it's working alright now :+1:

**Comment by roired** [comment]
@Begasus, I'm building CudaText directly from the sourcecode in Lazarus, adding the required dependencies (lpk files) to the Lazarus IDE. Once all dependencies are added, I close Lazarus and reopen it to verify that the dependencies are loaded inside Lazarus and available for the project, then I load the CudaText project and Build it. The outcome is CudaText exec.
Dependencies I added them according to the CudaText doc (https://wiki.freepascal.org/CudaText#How_to_compile_CudaText)

Nonetheless, I had some issues when adding the LPK packages. That is why I closed Lazarus and reopen, to certify that the packages were loaded when Lazarus starts.

I'll have to retest again though. First test didn't work yesterday. Today it did work. Not sure why today it did.
But was a clean VM and with your libqt5pas, so looks like we are heading in the right direction.

Thanks!

**Comment by roired** [comment]
@Begasus , would it be possible to add the symlinks in the recipe? I mean, have the recipe create the libQt5Pas.so and the libQt5Pas.so.1.2 besides the libQt5Pas.so.1? That way I can remove them from the package and leave the package just with CudaText files.
Regards
RR

**Comment by Begasus** [comment]
@roired the libQt5Pas.so should be in the _devel package?

**Comment by roired** [comment]
Ufffff... XD... Such question needs a pro to answer... 
I have no idea about that. I just saw that when I install libQt5Pas 1.2.9, two files appear inside the /boot/system/lib, libQt5Pas.so.1 (symlink) and libQt5Pas.so.1.2.9. 
I presumed that the symlink there was created by the recipe,  if so, the other two symlinks could also be generated there.
Mostly because looks like those symlinks are needed. Not sure though. I might need to rebuild the package without them and test again to confirm. 

Anyway, I have to recompile CudaText, as just found out something yesterday regarding Lazarus doc that might help.

I'm walking blind through this path. Learning each day a little bit.
XD

**Comment by Begasus** [comment]
Both /boot/system/lib and /boot/system/develop/lib should be include in the search $PATH, so having the base and the _devel package installed should be enough for CudaText to find them, if not I could look into putting them all in the base package (don't have Haiku running atm so can't check if headers are involved in the _devel package ;) )

**Comment by roired** [comment]
@Begasus , no idea about that. I just checked that the installed libQt5Pas 1.2.6 does that. That is, installs libQt5Pas.so.1.2.6 in /boot/system/lib and then adds the links libQt5Pas.so, libQt5Pas.so.1 and libQt5Pas.so.1.2.6 in /boot/system/lib. I don't know yet if this is the right way to do it as my knowledge on Haiku lib placement is zero. :(

Nonetheless... Next week I presume I'll have time to get back to it and will do some testing, because, iirc, with the libQt5Pas.so.1.2.9 and the link libQt5Pas.so.1 didn't work.

I'll redo the test as soon as I can.
Thanks,
Regards,
RR

**Comment by Begasus** [comment]
I think this could be closed?

**Comment by roired** [comment]
Thanks a lot @Begasus!! 
Close it now!
Regards,
RR
